In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

---

## Split the Data into Training and Testing Sets

#### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

###### Read the CSV file from the Resources folder into a Pandas DataFrame
###### YOUR CODE HERE!
###### Review the DataFrame
###### YOUR CODE HERE!

In [2]:
file_reading = Path("Resources/lending_data.csv")
lending_raw = pd.read_csv(file_reading)
lending_raw.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

###### Separate the data into labels and features
###### Separate the y variable, the labels
###### YOUR CODE HERE!]
###### Separate the X variable, the features
###### YOUR CODE HERE!

In [3]:
y = lending_raw["loan_size"]
y

0        10700.0
1         8400.0
2         9000.0
3        10700.0
4        10800.0
          ...   
77531    19100.0
77532    17700.0
77533    17600.0
77534    16300.0
77535    15600.0
Name: loan_size, Length: 77536, dtype: float64

In [4]:
X = lending_raw.drop(columns="loan_size")
X

interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0              7.672            52800        0.431818                5   
1              6.692            43600        0.311927                3   
2              6.963            46100        0.349241                3   
3              7.664            52700        0.430740                5   
4              7.698            53000        0.433962                5   
...              ...              ...             ...              ...   
77531         11.261            86600        0.653580               12   
77532         10.662            80900        0.629172               11   
77533         10.595            80300        0.626401               11   
77534         10.068            75300        0.601594               10   
77535          9.742            72300        0.585062                9   

       derogatory_marks  total_debt  loan_status  
0                     1       22800            0  
1                     0       13600            0  
2                     0       16100            0  
3                     1       22700            0  
4                     1       23000            0  
...                 ...         ...          ...  
77531                 2       56600            1  
77532                 2       50900            1  
77533                 2       50300            1  
77534                 2       45300            1  
77535                 2       42300            1  

[77536 rows x 7 columns]

#### Step 3: Split the data into training and testing datasets by using `train_test_split`.

###### Import the train_test_learn module
###### Split the data using train_test_split >>>> placed in the top <<<<<
###### Assign a random_state of 1 to the function
###### YOUR CODE HERE!

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

---

## Create a Logistic Regression Model with the Original Data

#####  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

#### 1
###### Import the LogisticRegression module from SKLearn >>>> placed in the top<<<<<<<
###### Instantiate the Logistic Regression model
###### Assign a random_state parameter of 1 to the model
#### 2
###### Fit the model using training data


In [8]:
classifier = LogisticRegression(solver='lbfgs', max_iter=200, random_state=1, verbose=1)
lreg = classifier.fit(X_train, y_train)

c:\Users\AndBe\anaconda3\envs\dev_2\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [13]:
lreg

LogisticRegression(max_iter=200, random_state=1, verbose=1)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [9]:
training_p = lreg.predict(X_train)
testing_p = lreg.predict(X_test)

In [ ]:
# Make a prediction using the testing data
# YOUR CODE HERE!

### Step 3: Evaluate the model’s performance by doing the following:

* Generate a confusion matrix.

* Print the classification report.

In [10]:
training_m = confusion_matrix(y_train, training_p)
print(training_m)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
training_r = classification_report(y_test, testing_p)
print(training_r)


              precision    recall  f1-score   support

      5200.0       0.00      0.00      0.00         2
      5600.0       0.00      0.00      0.00         2
      5700.0       0.00      0.00      0.00         5
      5800.0       0.00      0.00      0.00         7
      5900.0       0.00      0.00      0.00         6
      6000.0       0.00      0.00      0.00         6
      6100.0       0.00      0.00      0.00        12
      6200.0       0.00      0.00      0.00        14
      6300.0       0.00      0.00      0.00        15
      6400.0       0.00      0.00      0.00        22
      6500.0       0.00      0.00      0.00        39
      6600.0       0.00      0.00      0.00        28
      6700.0       0.00      0.00      0.00        39
      6800.0       0.00      0.00      0.00        50
      6900.0       0.00      0.00      0.00        71
      7000.0       0.00      0.00      0.00        72
      7100.0       0.00      0.00      0.00        81
      7200.0       0.00    

c:\Users\AndBe\anaconda3\envs\dev_2\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\AndBe\anaconda3\envs\dev_2\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\AndBe\anaconda3\envs\dev_2\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
# Generate a confusion matrix for the model
# YOUR CODE HERE!

In [ ]:
# Print the classification report for the model
# YOUR CODE HERE!

### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** With an accuracy of only 36%, the model can hardly be considered precise. Several factors could be contributing to this low performance. The robust number of rows and the scarcity of columns might be causing a mismatch in outcomes. For instance, income alone may not fully capture an individual's financial history. Spending habits can vary significantly within the same income bracket and across different brackets. Additionally, the type of debt—whether housing, credit card, auto, or educational—is not differentiated in the data, yet these differences can lead to vastly different outcomes.

Moreover, loan size can vary for numerous reasons, further complicating the model's accuracy. Factors such as age and education level might also play crucial roles in enhancing the model. For example, a 44-year-old with a middle-class income might show a high level of debt on paper, whereas a 22-year-old with a high income and lower debt levels might appear more financially stable.

Even the number of accounts could be misleading. For example, individuals might open credit accounts for various reasons, such as dental work, where a person applies for credit to afford necessary treatments.
I believe that when an individual applies for a loan through a peer-to-peer lending service, it is valuable to understand them more holistically. This approach could provide a more comprehensive picture through insights into their habits and commitments. Traditionally, before the advent of credit scores, lending required a degree of trust. Extending a loan to a stranger with no demonstrated commitment and an unknown personal history was considered risky.


---